import { useEffect, useRef, useState } from "react";
import { AlignCenter, AlignJustify, AlignLeft, AlignRight, Bold, ChevronDown, Code2, Eraser, Highlighter, Image as ImageIcon, Italic, Link, List, ListOrdered, Redo2, Table2, Underline, Undo2 } from "lucide-react";
import { Button, Modal } from "../../../ui";
import "../aiStackScreens-a.css";
// LMS_K12's `TemplateHtmlEditor` (via G2G), with `TemplateTag` inlined from its api module.
// HP BRAIN PORT: same toolbar, same commands, same table picker and resizing, same code
// view and preview — restyled with ais-a- classes because HP Brain has no Tailwind. The
// preview opens in HP Brain's Modal (Escape closes, focus is trapped and returned) and its
// frame is sandboxed so a layout's markup can never run script in the app's origin.
type TemplateTag = { key: string; label: string };
type Props={value:string;onChange:(html:string)=>void;tags:TemplateTag[];disabled?:boolean};
const FONT_FAMILIES = ["Arial", "Arial Black", "Arial Narrow", "Book Antiqua", "Calibri", "Cambria", "Comic Sans MS", "Courier New", "Georgia", "Helvetica", "Impact", "Josefin Sans", "Lucida Console", "Lucida Sans Unicode", "Palatino Linotype", "Segoe UI", "Tahoma", "Times New Roman", "Trebuchet MS", "Verdana"] as const;
const COLOR_PALETTE = ["#000000","#374151","#9ca3af","#ef4444","#f97316","#eab308","#84cc16","#22c55e","#10b981","#06b6d4","#3b82f6","#8b5cf6","#ec4899","#ffffff"];
export function TemplateHtmlEditor({value,onChange,tags,disabled}:Props){
 const ref=useRef<HTMLDivElement>(null); const savedRangeRef=useRef<Range|null>(null); const [preview,setPreview]=useState(false); const [codeView,setCodeView]=useState(false); const [tablePicker,setTablePicker]=useState(false); const [tableSize,setTableSize]=useState({ rows: 5, columns: 5 }); const [tableGrid,setTableGrid]=useState({ rows: 5, columns: 5 }); const [fontColor,setFontColor]=useState("#000000"); const [highlightColor,setHighlightColor]=useState("#ffff00"); const [showFontColorPalette,setShowFontColorPalette]=useState(false); const [showHighlightColorPalette,setShowHighlightColorPalette]=useState(false); const [editorHeight,setEditorHeight]=useState(200); const heightStartRef=useRef<{y:number;height:number}|null>(null);
 useEffect(()=>{if(ref.current&&ref.current.innerHTML!==value)ref.current.innerHTML=value},[value]);
 const sync=()=>onChange(ref.current?.innerHTML??"");
 const saveSelection=()=>{const sel=window.getSelection();if(sel&&sel.rangeCount>0)savedRangeRef.current=sel.getRangeAt(0)};
 const cmd=(name:string,val?:string)=>{ref.current?.focus();if(savedRangeRef.current){const sel=window.getSelection();if(sel){sel.removeAllRanges();sel.addRange(savedRangeRef.current)}};if(name==="formatBlock")document.execCommand("defaultParagraphSeparator",false,"p");document.execCommand(name,false,name==="formatBlock"&&val?`<${val}>`:val);sync()};
 const Tool=({title,children,onClick}:{title:string;children:React.ReactNode;onClick:()=>void})=><Button type="button" variant="ghost" size="sm" className="ais-a-tool" title={title} aria-label={title} onMouseDown={e=>e.preventDefault()} onClick={onClick} disabled={disabled}>{children}</Button>;
 const link=()=>{const url=window.prompt("Link URL");if(url)cmd("createLink",url)}; const image=()=>{const url=window.prompt("Image URL");if(url)cmd("insertHTML",`<img src="${url.replace(/"/g,"&quot;")}" alt="" style="max-width:100%;height:auto;" />`)};
  const insertTable=(rows:number,columns:number)=>{const cells=Array.from({length:columns},()=>"<td>&nbsp;</td>").join("");cmd("insertHTML",`<table class="template-editor-table" style="width:100%;border-collapse:collapse"><tbody>${Array.from({length:rows},()=>`<tr>${cells}</tr>`).join("")}</tbody></table><p></p>`);setTablePicker(false)};
  const RESIZE_THRESHOLD=8;
  const findTableEdge=(e:MouseEvent)=>{const target=e.target;if(!(target instanceof HTMLElement))return null;const cell=target.closest("td,th");if(!cell)return null;const table=cell.closest("table") as HTMLTableElement;if(!table)return null;const cellRect=cell.getBoundingClientRect();const tableRect=table.getBoundingClientRect();if(Math.abs(e.clientX-cellRect.right)<RESIZE_THRESHOLD){const row=cell.closest("tr")!;const cells=Array.from(row.children);const colIndex=cells.indexOf(cell);if(colIndex<cells.length-1)return{type:"column" as const,table,cell:cell as HTMLElement,colIndex}}if(Math.abs(e.clientY-cellRect.bottom)<RESIZE_THRESHOLD){const row=cell.closest("tr")!;const rows=Array.from(table.rows);const rowIndex=rows.indexOf(row as HTMLTableRowElement);if(rowIndex<rows.length-1)return{type:"row" as const,table,cell:cell as HTMLElement,rowIndex}}if(Math.abs(e.clientX-tableRect.right)<RESIZE_THRESHOLD&&Math.abs(e.clientY-tableRect.bottom)<RESIZE_THRESHOLD)return{type:"table" as const,table};return null};
  const startTableResize=(e:MouseEvent,edge:{type:"column"|"row"|"table";table:HTMLTableElement;cell?:HTMLElement;colIndex?:number;rowIndex?:number})=>{e.preventDefault();const table=edge.table;const startX=e.clientX;const startY=e.clientY;if(edge.type==="column"&&edge.cell&&edge.colIndex!==undefined){const startWidth=edge.cell.offsetWidth;const colIndex=edge.colIndex;const onMove=(ev:MouseEvent)=>{const w=Math.max(20,startWidth+(ev.clientX-startX));table.querySelectorAll("tr").forEach(row=>{const cells=Array.from(row.querySelectorAll("td,th"));if(cells[colIndex])(cells[colIndex] as HTMLElement).style.width=`${w}px`})};const onUp=()=>{sync();document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)}else if(edge.type==="row"&&edge.cell&&edge.rowIndex!==undefined){const row=edge.cell.closest("tr")!;const startHeight=row.offsetHeight;const rowIndex=edge.rowIndex;const onMove=(ev:MouseEvent)=>{const h=Math.max(20,startHeight+(ev.clientY-startY));const rows=table.querySelectorAll("tr");if(rows[rowIndex])(rows[rowIndex] as HTMLElement).style.height=`${h}px`};const onUp=()=>{sync();document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)}else if(edge.type==="table"){const startWidth=table.offsetWidth;const startHeight=table.offsetHeight;const onMove=(ev:MouseEvent)=>{table.style.width=`${Math.max(100,startWidth+(ev.clientX-startX))}px`;table.style.height=`${Math.max(50,startHeight+(ev.clientY-startY))}px`};const onUp=()=>{sync();document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)}};
  const handleEditorMouseMove=(e:React.MouseEvent<HTMLDivElement>)=>{if(disabled)return;const edge=findTableEdge(e.nativeEvent);if(ref.current)ref.current.style.cursor=edge?edge.type==="column"?"col-resize":edge.type==="row"?"row-resize":"nwse-resize":""};
  const handleEditorMouseDown=(e:React.MouseEvent<HTMLDivElement>)=>{if(disabled)return;const edge=findTableEdge(e.nativeEvent);if(!edge)return;startTableResize(e.nativeEvent,edge)};
  const startHeightResize=(e:React.MouseEvent<HTMLDivElement>)=>{e.preventDefault();heightStartRef.current={y:e.clientY,height:editorHeight};const onMove=(ev:MouseEvent)=>{if(heightStartRef.current)setEditorHeight(Math.max(150,heightStartRef.current.height+(ev.clientY-heightStartRef.current.y)))};const onUp=()=>{heightStartRef.current=null;document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)};
 return <div className="ais-a-editor">
  <div className="ais-a-editor-toolbar" role="toolbar" aria-label="Formatting">
   <select aria-label="Block format" className="ais-a-editor-select" defaultValue="p" onMouseDown={saveSelection} disabled={disabled} onChange={e=>cmd("formatBlock",e.target.value)}><option value="p">Paragraph</option><option value="h1">Heading 1</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option><option value="h4">Heading 4</option><option value="h5">Heading 5</option><option value="h6">Heading 6</option><option value="blockquote">Quote</option></select>
   <select aria-label="Font family" className="ais-a-editor-select" onMouseDown={saveSelection} disabled={disabled} onChange={e=>cmd("fontName",e.target.value)}><option value="">Font</option>{FONT_FAMILIES.map(font=><option key={font} value={font}>{font}</option>)}</select><select aria-label="Font size" className="ais-a-editor-select" onMouseDown={saveSelection} disabled={disabled} onChange={e=>cmd("fontSize",e.target.value)}><option value="">Size</option><option value="2">Small</option><option value="3">Normal</option><option value="4">Large</option><option value="5">X-Large</option></select>
   <Tool title="Bold" onClick={()=>cmd("bold")}><Bold size={16} aria-hidden="true"/></Tool><Tool title="Italic" onClick={()=>cmd("italic")}><Italic size={16} aria-hidden="true"/></Tool><Tool title="Underline" onClick={()=>cmd("underline")}><Underline size={16} aria-hidden="true"/></Tool>
   <div className="ais-a-pop-anchor"><Button type="button" variant="ghost" size="sm" className="ais-a-tool ais-a-tool--wide" title="Text Color" aria-label="Text Color" aria-expanded={showFontColorPalette} disabled={disabled} onMouseDown={e=>{e.preventDefault();saveSelection()}} onClick={()=>setShowFontColorPalette(!showFontColorPalette)}><span className="ais-a-swatch-btn"><span className="ais-a-swatch-letter" style={{color:fontColor}}>A</span><span className="ais-a-swatch-bar" style={{backgroundColor:fontColor}}></span></span><ChevronDown size={12} className="ais-a-caret" aria-hidden="true"/></Button>{showFontColorPalette&&<div className="ais-a-palette"><div className="ais-a-palette-title">Text Color</div><div className="ais-a-palette-grid">{COLOR_PALETTE.map(c=><button key={c} type="button" aria-label={c} title={c} className="ais-a-swatch" style={{backgroundColor:c}} onClick={()=>{setFontColor(c);cmd('foreColor',c);setShowFontColorPalette(false)}}/>)}</div><input type="color" aria-label="Custom text color" value={fontColor} onChange={e=>{setFontColor(e.target.value);cmd('foreColor',e.target.value);setShowFontColorPalette(false)}} className="ais-a-palette-custom"/></div>}</div><div className="ais-a-pop-anchor"><Button type="button" variant="ghost" size="sm" className="ais-a-tool ais-a-tool--wide" title="Highlight Color" aria-label="Highlight Color" aria-expanded={showHighlightColorPalette} disabled={disabled} onMouseDown={e=>{e.preventDefault();saveSelection()}} onClick={()=>setShowHighlightColorPalette(!showHighlightColorPalette)}><span className="ais-a-swatch-btn"><Highlighter size={16} style={{color:highlightColor}} aria-hidden="true"/><span className="ais-a-swatch-bar" style={{backgroundColor:highlightColor}}></span></span><ChevronDown size={12} className="ais-a-caret" aria-hidden="true"/></Button>{showHighlightColorPalette&&<div className="ais-a-palette"><div className="ais-a-palette-title">Highlight Color</div><div className="ais-a-palette-grid">{COLOR_PALETTE.map(c=><button key={c} type="button" aria-label={c} title={c} className="ais-a-swatch" style={{backgroundColor:c}} onClick={()=>{setHighlightColor(c);cmd('hiliteColor',c);setShowHighlightColorPalette(false)}}/>)}</div><input type="color" aria-label="Custom highlight color" value={highlightColor} onChange={e=>{setHighlightColor(e.target.value);cmd('hiliteColor',e.target.value);setShowHighlightColorPalette(false)}} className="ais-a-palette-custom"/></div>}</div>
   <Tool title="Align left" onClick={()=>cmd("justifyLeft")}><AlignLeft size={16} aria-hidden="true"/></Tool><Tool title="Align center" onClick={()=>cmd("justifyCenter")}><AlignCenter size={16} aria-hidden="true"/></Tool><Tool title="Align right" onClick={()=>cmd("justifyRight")}><AlignRight size={16} aria-hidden="true"/></Tool><Tool title="Justify" onClick={()=>cmd("justifyFull")}><AlignJustify size={16} aria-hidden="true"/></Tool><Tool title="Bulleted list" onClick={()=>cmd("insertUnorderedList")}><List size={16} aria-hidden="true"/></Tool><Tool title="Numbered list" onClick={()=>cmd("insertOrderedList")}><ListOrdered size={16} aria-hidden="true"/></Tool><Tool title="Add link" onClick={link}><Link size={16} aria-hidden="true"/></Tool><Tool title="Add image" onClick={image}><ImageIcon size={16} aria-hidden="true"/></Tool><div className="ais-a-pop-anchor"><Button type="button" variant="ghost" size="sm" className="ais-a-tool" title="Insert table" aria-label="Insert table" aria-expanded={tablePicker} disabled={disabled} onMouseDown={event=>event.preventDefault()} onClick={()=>{setTableSize({rows:5,columns:5});setTableGrid({rows:5,columns:5});setTablePicker(open=>!open)}}><Table2 size={16} aria-hidden="true"/></Button>{tablePicker&&<div className="ais-a-table-picker" style={{width:`${tableGrid.columns*18+16}px`}}><div className="ais-a-table-grid" style={{gridTemplateColumns:`repeat(${tableGrid.columns}, minmax(0, 1fr))`}}>{Array.from({length:tableGrid.rows*tableGrid.columns},(_,index)=>{const row=Math.floor(index/tableGrid.columns)+1;const column=index%tableGrid.columns+1;const selected=row<=tableSize.rows&&column<=tableSize.columns;return <button key={index} type="button" aria-label={`Insert ${row} by ${column} table`} className={`ais-a-table-cell${selected ? " ais-a-table-cell--on" : ""}`} onMouseEnter={()=>{setTableSize({rows:row,columns:column});setTableGrid(current=>({rows:row===current.rows?Math.min(10,current.rows+1):current.rows,columns:column===current.columns?Math.min(10,current.columns+1):current.columns}))}} onMouseDown={event=>event.preventDefault()} onClick={()=>insertTable(row,column)}/>})}</div><div className="ais-a-table-size">{tableSize.rows} x {tableSize.columns}</div></div>}</div><Tool title="Horizontal line" onClick={()=>cmd("insertHorizontalRule")}>-</Tool><Tool title={codeView ? "Visual editor" : "Code view"} onClick={()=>{sync();setCodeView(current=>!current)}}><Code2 size={16} aria-hidden="true"/></Tool><Tool title="Clear formatting" onClick={()=>cmd("removeFormat")}><Eraser size={16} aria-hidden="true"/></Tool><Tool title="Undo" onClick={()=>cmd("undo")}><Undo2 size={16} aria-hidden="true"/></Tool><Tool title="Redo" onClick={()=>cmd("redo")}><Redo2 size={16} aria-hidden="true"/></Tool>
   {/* Hidden when there are no tags to insert: a generated report is already-rendered
       data with no <<tokens>> in it, and an empty picker is a control that does nothing. */}
   {tags.length>0&&<select aria-label="Insert template variable" className="ais-a-editor-select" onMouseDown={saveSelection} defaultValue="" disabled={disabled} onChange={e=>{if(e.target.value){cmd("insertHTML",`&lt;&lt; ${e.target.value} &gt;&gt;`);e.target.value=""}}}><option value="">Insert template variable...</option>{tags.map(t=><option key={t.key} value={t.key}>{t.key} - {t.label}</option>)}</select>}<Button type="button" size="sm" variant="secondary" disabled={disabled} onClick={()=>setPreview(true)}>Preview</Button>
  </div>{codeView ? <textarea aria-label="HTML content code view" value={value} disabled={disabled} onChange={event=>onChange(event.target.value)} style={{height:editorHeight}} className="ais-a-editor-code" /> : <div ref={ref} contentEditable={!disabled} suppressContentEditableWarning role="textbox" aria-multiline="true" aria-label="HTML content visual editor" onInput={sync} onBlur={sync} onMouseMove={handleEditorMouseMove} onMouseDown={handleEditorMouseDown} style={{height:editorHeight}} className="ais-a-editor-surface"/>}
  <Modal open={preview} onClose={()=>setPreview(false)} title="Template preview" size="lg">{preview&&<iframe title="Template preview" srcDoc={ref.current?.innerHTML??value} sandbox="allow-same-origin" className="ais-a-editor-preview"/>}</Modal>
   {!disabled&&<div className="ais-a-editor-resize" onMouseDown={startHeightResize} title="Drag to resize editor height" aria-hidden="true"/>}
 </div>
}
